# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def shared_pods
    pod 'RealmSwift'
end

target 'PhoneBookV2' do
    platform :ios, '9.0'
    shared_pods
end

target 'watchapp' do

end

target 'watchapp Extension' do
    platform :watchos, '2.0'
    shared_pods
end
